version: '3'
services:
  postgres:
    container_name: postgres${SHARDER}
    image: postgres:14
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ../config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ../sharder${SHARDER}/data/postgresql:/var/lib/postgresql/data
      - ../sql_script/:/docker-entrypoint-initdb.d/
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      default:
    restart: always
  
  postgres-post:
    container_name: postgres-post${SHARDER}
    image: postgres:14
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ../bin:/0chain/bin
      - ../sql:/0chain/sql
      - ../sql_script/:/docker-entrypoint-initdb.d/
    links:
      - postgres:postgres
  
  sharder:
    container_name: sharder${SHARDER}
    image: 0chaindev/sharder:staging
    environment:
      - POSTGRES_HOST=postgres${SHARDER}
      - DOCKER=true
    depends_on:
      - postgres
    volumes:
      - ../config:/0chain/config
      - /mnt/hdd/sharder${SHARDER}/log:/0chain/log
      - /mnt/hdd/sharder${SHARDER}/data:/0chain/data
    ports:
      - "717${SHARDER}:717${SHARDER}"
    networks:
      default:
      testnet0:
        ipv4_address: 198.18.0.8${SHARDER}
    command: 
      - /bin/sh
      - -c 
      - mkdir -p /0chain/data/blocks && mkdir -p /0chain/data/rocksdb && ./bin/sharder --deployment_mode 0 --keys_file config/b0snode${SHARDER}_keys.txt
    restart: always

networks:
  default:
    driver: bridge
  testnet0:
    external: true

volumes:
  data:
  config:
  bin:
