scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:9487

- job_name: monitoring
  scrape_interval: 5s
  static_configs:
  - targets:
    - node-exporter:9100
