name: chimney_script_config_change_PR

on:
  workflow_dispatch:

jobs:
  ChimneyScriptUpdate:
    runs-on: arc-runner
    steps:
      - uses: actions/checkout@v3

      - name: "Clone Blobber Repo"
        uses: actions/checkout@v3
        with:
          ref: update/chimney-script
          repository: 0chain/blobber
          fetch-depth: 1
          path: ./blobber

      - name: "Copy Config Files"
        run: |
           cp ./blobber/config/0chain_blobber.yaml  ./config/0chain_blobber.yaml
           cp ./blobber/config/0chain_validator.yaml  ./config/0chain_validator.yaml

  PR:
    runs-on: 'arc-runner'
    needs: [ChimneyScriptUpdate]
    steps:
      - uses: actions/checkout@v3

      - name: Raise PR
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          source_branch: feature/config-ci
          target_branch: sprint111
          title: Update Chimney Script Config
          body: testing chimney script
          reviewer: boddumanohar    
